/**************************************************************************************************************
*   @author         Persistent Systems
*   @date           26/09/2018
*   @description    This class is used to  define constant values and to set order which are used to display records in Account,Contact and Lead pages
***************************************************************************************************************/
public with sharing class DraupConstants {
    public static final List<Object> OVERVIEW=new List<Object>{'Overview',1};
    public static final List<Object> EXPERIENCES=new List<Object>{'Experience',2};
    public static final List<Object> PSYCHOLOGICAL_ANALYSIS=new List<Object>{'Draup Psychological Analysis',3};
    public static final List<Object> OUTSOURCING=new List<Object>{'Outsourcing',2};
    public static final List<Object> GLOBALIZATION=new List<Object>{'Globalization',3};
    public static final List<Object> TECHSTACK=new List<Object>{'Digital Tech Stack',4};
    public static final List<Object> STARTEGIC_SIGNALS=new List<Object>{'Strategic Signals',5};
    public static final List<Object> EXECUTIVE_MOVEMENT=new List<Object>{'Executive Movement',6};
    public static final List<Object> HIRING=new List<Object>{'Hiring',7};
    
}